gvnc: vpro helper

diff --git a/bin/gvnc b/bin/gvnc
--- a/bin/gvnc
+++ b/bin/gvnc
@@ -1,27 +1,32 @@
 #!/bin/bash
 vm="$1"
 [ "${vm##*.}" == "t" ] && vm=${vm}etaneutral.net
-info=($(ssh openstack.tetaneutral.net -p 2222 -l root -- "mysql nova --skip-column-names --batch -e 'select host, uuid from instances where display_name=\"$vm\" and deleted=0;'"))
+[ "${vm##*.}" == "v" ] && vm=${vm%%.*}-vpro
 
-if [ "${info[0]}" == "mysql" ]; then
-    echo "Error in mysql request"
-    exit 1
+if [ "${vm##*-}" == "vpro" ]; then
+    echo "$vm via nagios.t proto vnc"
+    URL=vnc://localhost:5910/
+    ssh -N nagios.tetaneutral.net -p 2222 -l root -L 5910:$vm:5900 &
+    PID=$!
+else
+    info=($(ssh openstack.tetaneutral.net -p 2222 -l root -- "mysql nova --skip-column-names --batch -e 'select host, uuid from instances where display_name=\"$vm\" and deleted=0;'"))
+
+    if [ "${info[0]}" == "mysql" ]; then
+        echo "Error in mysql request"
+        exit 1
+    fi
+
+    hypervisor=${info[0]}.tetaneutral.net
+    uuid=${info[1]}
+    spice_port=$(ssh ${hypervisor} -p 2222 -l root virsh domdisplay ${uuid} | awk -F: '{print $3}')
+    URL="spice://localhost:5910/"
+
+    echo "$vm on $hypervisor proto spice port $spice_port"
+    ssh -N $hypervisor -p 2222 -l root -L 5910:localhost:${spice_port} &
+    PID=$!
 fi
 
-hypervisor=${info[0]}.tetaneutral.net
-uuid=${info[1]}
-spice_port=$(ssh ${hypervisor} -p 2222 -l root virsh domdisplay ${uuid} | awk -F: '{print $3}')
-
-echo "$vm on $hypervisor port $spice_port"
-ssh -N $hypervisor -p 2222 -l root -L 5910:localhost:${spice_port} &
-pid=$!
-
-
-cleanup(){
-    kill $pid
-}
-
+cleanup(){ kill $PID ; }
 trap cleanup EXIT
-
 sleep 2
-remote-viewer spice://localhost:5910/
+remote-viewer $URL
